import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  ACCEPTED_LABEL,
  BACKLOG_PATH,
  addedRowIds,
  appendTodoRows,
  findTriageComments,
  inlineCode,
  lintBacklog,
  nextIds,
  parseBacklog,
  parseTriage,
  promote,
  pullRequestBody,
  pullRequestTitle,
  renderRow,
  run,
  validateEntries,
} from './backlog-promotion.mjs';

const repositoryRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const realBacklog = readFileSync(join(repositoryRoot, BACKLOG_PATH), 'utf8');

const REPOSITORY = 'avshukan/rank-vote';
const BASE_SHA = 'b'.repeat(40);
const BLOB_SHA = 'f'.repeat(40);
const BRANCH = 'docs/backlog-promote-62';

const MARKERS = [
  `<!-- gh-aw-agentic-workflow: Issue triage recommendation, engine: copilot, model: auto, id: 1, workflow_id: issue-triage, run: https://github.com/${REPOSITORY}/actions/runs/1 -->`,
  `<!-- gh-aw-workflow-call-id: ${REPOSITORY}/issue-triage -->`,
].join('\n');

// The recommendation the issue-triage workflow posted on #62, verbatim: its
// Notes run to 54 characters against a 51-character column.
const ISSUE_62_TRIAGE = `## Triage recommendation

**Verdict:** Keep
**Proposed backlog title:** Add short poll links
**Type:** Quality — shortening poll share URLs is a UX improvement that makes the product easier to use without adding new functionality
**Level:** Low — the current UUID links work; this is a nice-to-have convenience improvement with significant implementation complexity (ID namespace, collision avoidance, redirect layer)

### Dependencies / context

- ID-2 (Done) — Share poll link: the feature being improved
- \`docs/01-mvp-scope.md\` — core "generate unique link" constraint; UUIDs satisfy it, short links would be an enhancement
- No duplicate found in backlog or open issues

### Candidate backlog entry

- **Title:** Add short poll links
- **Type:** Quality
- **Level:** Low
- **State:** —
- **Notes:** Replace/alias UUID with short ID; needs redirect layer
- **Dependencies / context:** ID-2

_Recommendation only — nothing was changed. The repository owner decides;
the backlog ID and row are assigned at backlog promotion._
_To accept and promote this item to the backlog, apply the \`triage: accepted\` label._

> Generated by [Issue triage recommendation](https://github.com/avshukan/rank-vote/actions/runs/36687156633) for #62 · copilot · auto

<!-- gh-aw-agentic-workflow: Issue triage recommendation, engine: copilot, model: auto, id: 36687156633, workflow_id: issue-triage, run: https://github.com/avshukan/rank-vote/actions/runs/36687156633 -->
<!-- gh-aw-workflow-call-id: avshukan/rank-vote/issue-triage -->`;

const DEFAULT_ENTRY = {
  Title: 'Add short poll links',
  Type: 'Quality',
  Level: 'Low',
  State: '—',
  Notes: 'Short IDs for poll URLs; needs a redirect',
  'Dependencies / context': 'ID-2',
};

function maxBacklogId(backlog) {
  return Math.max(
    0,
    ...[...backlog.todo.rows, ...backlog.done.rows].map((row) => Number(row.cells[0])),
  );
}

function nextBacklogId(backlog, reservedIds = []) {
  return nextIds(backlog, reservedIds, 1)[0];
}

// A recommendation in the issue-triage comment format; a field set to
// `undefined` is left out.
function triageBody({ verdict = 'Keep', entries = [{}] } = {}) {
  const sections = entries.map((entry) =>
    [
      '### Candidate backlog entry',
      '',
      ...Object.entries({ ...DEFAULT_ENTRY, ...entry })
        .filter(([, value]) => value !== undefined)
        .map(([name, value]) => `- **${name}:** ${value}`),
      '',
    ].join('\n'),
  );
  return [
    '## Triage recommendation',
    '',
    `**Verdict:** ${verdict}`,
    '**Proposed backlog title:** Add short poll links',
    '',
    '### Dependencies / context',
    '',
    '- ID-2',
    '',
    ...(verdict === 'Keep' ? sections : []),
    '_Recommendation only — nothing was changed._',
    '',
    MARKERS,
  ].join('\n');
}

function triageComment(body = triageBody(), overrides = {}) {
  return {
    id: 5906921993,
    user: { login: 'github-actions[bot]', type: 'Bot' },
    body,
    html_url: `https://github.com/${REPOSITORY}/issues/62#issuecomment-5906921993`,
    created_at: '2026-09-30T08:05:47Z',
    updated_at: '2026-09-30T08:05:47Z',
    ...overrides,
  };
}

const httpError = (status, message = `HTTP ${status}`) =>
  Object.assign(new Error(message), { status });

// An in-memory GitHub REST API that records every request.
function fakeGitHub({
  permission = 'admin',
  issue = {},
  comments = [triageComment()],
  promotionPulls = [],
  openPulls = [],
  pullFiles = {},
  branches = [],
  failures = {},
  backlog = realBacklog,
} = {}) {
  const state = { branches: new Set(branches), comments: [], calls: [] };
  const branchOf = (route) => route.split('/heads/')[1];
  const routes = [
    ['GET /repos/{owner}/{repo}/collaborators/{username}/permission', () => ({ permission })],
    [
      'GET /repos/{owner}/{repo}/issues/{issue_number}',
      () => ({ number: 62, state: 'open', labels: [{ name: ACCEPTED_LABEL }], ...issue }),
    ],
    [
      'GET /repos/{owner}/{repo}/pulls',
      (params) => (params.state === 'all' ? promotionPulls : openPulls),
    ],
    ['GET /repos/{owner}/{repo}/issues/{issue_number}/comments', () => comments],
    [
      'GET /repos/{owner}/{repo}/pulls/{pull_number}/files',
      (params) => pullFiles[params.pull_number] ?? [],
    ],
    ['GET /repos/{owner}/{repo}/git/ref/heads/main', () => ({ object: { sha: BASE_SHA } })],
    [
      (route) => route.startsWith('GET /repos/{owner}/{repo}/git/ref/heads/'),
      (params, route) => {
        if (state.branches.has(branchOf(route))) return { object: { sha: BASE_SHA } };
        throw httpError(404);
      },
    ],
    [
      `GET /repos/{owner}/{repo}/contents/${BACKLOG_PATH}`,
      () => ({
        sha: BLOB_SHA,
        encoding: 'base64',
        content: Buffer.from(backlog).toString('base64'),
      }),
    ],
    [
      'POST /repos/{owner}/{repo}/git/refs',
      (params) => {
        const branch = params.ref.replace('refs/heads/', '');
        if (state.branches.has(branch)) throw httpError(422, 'Reference already exists');
        state.branches.add(branch);
        return {};
      },
    ],
    [
      `PUT /repos/{owner}/{repo}/contents/${BACKLOG_PATH}`,
      () => ({ commit: { sha: 'c'.repeat(40) } }),
    ],
    [
      'POST /repos/{owner}/{repo}/pulls',
      () => ({ number: 70, html_url: `https://github.com/${REPOSITORY}/pull/70` }),
    ],
    [
      (route) => route.startsWith('DELETE /repos/{owner}/{repo}/git/refs/heads/'),
      (params, route) => {
        state.branches.delete(branchOf(route));
        return {};
      },
    ],
    [
      'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
      (params) => {
        state.comments.push(params.body);
        return {};
      },
    ],
  ];
  async function request(route, params = {}) {
    state.calls.push({ route, params });
    if (failures[route]) throw failures[route];
    const match = routes.find(([key]) => (typeof key === 'string' ? key === route : key(route)));
    if (!match) throw new Error(`unexpected request: ${route}`);
    return { data: await match[1](params, route) };
  }
  return {
    request,
    paginate: async (route, params) => (await request(route, params)).data,
    state,
    writes: () =>
      state.calls
        .filter(({ route }) => !route.startsWith('GET '))
        .filter(({ route }) => !route.endsWith('/comments'))
        .map(({ route }) => route.split(' ')[0] + ' ' + route.split('{repo}')[1]),
  };
}

function fakeCore() {
  const core = { failed: null, notices: [], warnings: [], summaryText: '' };
  core.setFailed = (message) => (core.failed = message);
  core.notice = (message) => core.notices.push(message);
  core.warning = (message) => core.warnings.push(message);
  core.info = () => {};
  core.summary = {
    addRaw(text) {
      core.summaryText += text;
      return this;
    },
    async write() {},
  };
  return core;
}

function fakeContext(overrides = {}) {
  return {
    repo: { owner: 'avshukan', repo: 'rank-vote' },
    serverUrl: 'https://github.com',
    runId: 99,
    eventName: 'issues',
    payload: {
      sender: { login: 'avshukan' },
      repository: { default_branch: 'main' },
      issue: { number: 62 },
    },
    ...overrides,
  };
}

async function promote62(github, options = {}) {
  const core = fakeCore();
  const result = await promote({
    github,
    context: fakeContext(),
    core,
    issueNumber: 62,
    ...options,
  });
  return { result, core, comment: github.state.comments.join('\n') };
}

// ---------------------------------------------------------------------------
// docs/backlog.md format

test('docs/backlog.md follows its fixed-width Format rules', () => {
  assert.deepEqual(lintBacklog(realBacklog), []);
});

test('the backlog lint reports duplicate IDs, overflow, misalignment and unknown values', () => {
  const lines = realBacklog.split('\n');
  const row = (id) => lines.findIndex((line) => line.startsWith(`| ${id} `));
  lines[row(6)] = lines[row(19)];
  lines[row(20)] = lines[row(20)].replace('Quality ', 'Feature ');
  lines[row(8)] = lines[row(8)].replace(
    'Instant-runoff voting',
    'Instant-runoff voting'.padEnd(60, '!'),
  );
  lines[row(9)] = lines[row(9)].replace('| Value ', '|  Value');
  const problems = lintBacklog(lines.join('\n')).join('\n');

  assert.match(problems, /ID 19 is already used on line/);
  assert.match(problems, /Type `Feature` is not a Legend value/);
  assert.match(problems, /Notes is \d+ characters; the column fits 51/);
  assert.match(problems, /cells are not padded to the column widths/);
});

test('rows are padded to the ruler: 120 characters, Done IDs right-aligned', () => {
  const backlog = parseBacklog(realBacklog);
  const actualId = nextBacklogId(backlog);
  const todo = renderRow(backlog.todo.columns, [
    String(actualId),
    'Add short poll links',
    'Quality',
    'Low',
    '—',
    'x',
  ]);
  const done = renderRow(backlog.done.columns, [
    String(actualId),
    'Add short poll links',
    'Quality',
    'Low',
    'x',
  ]);

  assert.equal([...todo].length, 120);
  assert.ok(
    todo.startsWith(
      `| ${String(actualId).padEnd(backlog.todo.columns[0].width, ' ')} | Add short poll links`,
    ),
  );
  assert.equal([...done].length, 120);
  assert.ok(
    done.startsWith(
      `| ${String(actualId).padStart(backlog.done.columns[0].width, ' ')} | Add short poll links`,
    ),
  );
});

test('new rows are appended to the end of Todo and keep the format', () => {
  const backlog = parseBacklog(realBacklog);
  const nextId = nextBacklogId(backlog);
  const entry = {
    ID: String(nextId),
    Title: 'Add short poll links',
    Type: 'Quality',
    Level: 'Low',
    State: '—',
    Notes: 'x',
  };
  const { rows, text } = appendTodoRows(backlog, [entry]);
  const lines = text.split('\n');
  const inserted = lines.indexOf(rows[0]);
  const previous = backlog.todo.rows.at(-1)?.cells?.[0] ?? '0';

  assert.ok(lines[inserted - 1].startsWith(`| ${previous} `), 'follows the prior Todo row');
  assert.equal(lines[inserted + 1], '');
  assert.equal(lines.length, backlog.lines.length + 1);
  assert.deepEqual(lintBacklog(text), []);
});

test('the next ID follows the backlog and every ID an open pull request adds', () => {
  const backlog = parseBacklog(realBacklog);
  const patch = '@@ -117,0 +118,2 @@\n+| 36  | Other item |\n+|  37 | Done item |\n-| 35 | gone |';
  const reserved = addedRowIds(patch);
  const expectedFirst = Math.max(maxBacklogId(backlog), ...reserved) + 1;

  assert.deepEqual(addedRowIds(patch), [36, 37]);
  assert.deepEqual(nextIds(backlog, [], 1), [maxBacklogId(backlog) + 1]);
  assert.deepEqual(nextIds(backlog, reserved, 2), [expectedFirst, expectedFirst + 1]);
});

// ---------------------------------------------------------------------------
// The triage recommendation

test('only the issue-triage workflow comment counts as the recommendation', () => {
  const genuine = triageComment();
  const comments = [
    genuine,
    { ...genuine, user: { login: 'avshukan', type: 'User' } },
    { ...genuine, user: { login: 'github-actions[bot]', type: 'User' } },
    { ...genuine, body: genuine.body.replace(/<!-- gh-aw-workflow-call-id[^>]*>/, '') },
    { ...genuine, body: genuine.body.replaceAll('issue-triage', 'other-workflow') },
    { ...genuine, body: `> quoted\n\n${genuine.body}` },
    { ...genuine, body: '### Backlog promotion failed\n\nReason' },
  ];

  assert.deepEqual(findTriageComments(comments, REPOSITORY), [genuine]);
  assert.deepEqual(findTriageComments(comments, 'someone/fork'), []);
});

test('a recommendation is parsed as written, including a split', () => {
  const parsed = parseTriage(triageBody({ entries: [{}, { Title: 'Second item', Notes: 'Two' }] }));

  assert.deepEqual(parsed.verdicts, ['Keep']);
  assert.equal(parsed.entries.length, 2);
  assert.equal(parsed.entries[1].Title, 'Second item');
  assert.equal(parsed.entries[0]['Dependencies / context'], 'ID-2');
  assert.deepEqual(parsed.duplicates, []);
});

test('a valid entry passes unchanged and starts with State —', () => {
  const backlog = parseBacklog(realBacklog);
  const { entries, problems } = validateEntries(parseTriage(triageBody()), backlog);

  assert.deepEqual(problems, []);
  assert.deepEqual(entries, [
    {
      Title: 'Add short poll links',
      Type: 'Quality',
      Level: 'Low',
      State: '—',
      Notes: 'Short IDs for poll URLs; needs a redirect',
      dependencies: 'ID-2',
    },
  ]);
});

test('overlong values are reported with their length and limit, never shortened', () => {
  const backlog = parseBacklog(realBacklog);
  const { problems } = validateEntries(parseTriage(ISSUE_62_TRIAGE), backlog);

  assert.deepEqual(problems, [
    'The candidate entry: Notes is 54 characters; the `Todo` Notes column fits 51: ' +
      '`Replace/alias UUID with short ID; needs redirect layer`',
  ]);
});

test('entries that would break the table or the process are refused', () => {
  const backlog = parseBacklog(realBacklog);
  const entries = [
    { Title: 'A | B' },
    { Title: 'Add 🎉 support' },
    { Title: 'Fixes #3 quickly' },
    { Type: 'Feature' },
    { Level: 'Urgent' },
    { State: 'Ready' },
    { Notes: undefined },
    { Notes: '…' },
  ];
  const problems = validateEntries(parseTriage(triageBody({ entries })), backlog).problems.join(
    '\n',
  );

  assert.match(problems, /1 of 8: Title contains `\|`/);
  assert.match(problems, /2 of 8: Title contains a character that is not one column wide/);
  assert.match(problems, /3 of 8: Title contains an issue-closing reference/);
  assert.match(
    problems,
    /4 of 8: Type `Feature` is not a Legend value \(Value, Quality, Refactor, Ops\)/,
  );
  assert.match(problems, /5 of 8: Level `Urgent` is not a Legend value/);
  assert.match(problems, /6 of 8: State is `Ready`; a new backlog item starts with `—`/);
  assert.match(problems, /7 of 8 has no `- \*\*Notes:\*\*` line/);
  assert.match(problems, /8 of 8: Notes is empty/);
});

// ---------------------------------------------------------------------------
// Pull request and Issue texts

test('the pull request title names one item, or counts a split', () => {
  assert.equal(
    pullRequestTitle(62, [{ Title: 'Add short poll links' }]),
    'backlog: promote #62 — Add short poll links',
  );
  assert.equal(
    pullRequestTitle(62, [{ Title: 'A' }, { Title: 'B' }]),
    'backlog: promote #62 (2 items)',
  );
});

test('the pull request body closes the Issue and quotes untrusted text as code', () => {
  const body = pullRequestBody({
    issueNumber: 62,
    entries: [{ ID: '36', dependencies: 'fixes #1, ask @someone' }],
    rows: ['| 36  | row |'],
    comment: triageComment(undefined, { updated_at: '2026-09-30T09:00:00Z' }),
    runUrl: 'https://github.com/run',
  });

  assert.match(body, /^Closes #62$/m);
  assert.match(body, /```text\n\| 36 {2}\| row \|\n```/);
  assert.match(body, /ID-36: `fixes #1, ask @someone`/);
  assert.match(body, /the triage comment was edited/i);
  assert.match(body, /<!-- backlog-promotion: issue=62; ids=36; triage-comment=5906921993 -->/);
});

test('inline code survives backticks in the value', () => {
  assert.equal(inlineCode('plain'), '`plain`');
  assert.equal(inlineCode('`pnpm dev` orphans'), '`` `pnpm dev` orphans ``');
});

// ---------------------------------------------------------------------------
// The whole promotion

test('an accepted Issue becomes a Todo row on a new branch and a pull request', async () => {
  const backlog = parseBacklog(realBacklog);
  const nextId = nextBacklogId(backlog);
  const github = fakeGitHub();
  const { result, core, comment } = await promote62(github);

  assert.equal(result.outcome, 'promoted');
  assert.deepEqual(github.writes(), [
    'POST /git/refs',
    `PUT /contents/${BACKLOG_PATH}`,
    'POST /pulls',
  ]);
  const [ref, commit, pull] = github.state.calls.filter(({ route }) => !route.startsWith('GET '));
  assert.deepEqual(ref.params.ref, `refs/heads/${BRANCH}`);
  assert.equal(ref.params.sha, BASE_SHA);
  assert.equal(commit.params.sha, BLOB_SHA);
  assert.equal(commit.params.branch, BRANCH);
  assert.equal(commit.params.message, 'backlog: promote #62 — Add short poll links');
  const written = Buffer.from(commit.params.content, 'base64').toString('utf8');
  assert.equal(written, appendTodoRows(backlog, [{ ...result.plan.entries[0] }]).text);
  assert.match(
    written,
    new RegExp(`\\| ${nextId} +\\| Add short poll links +\\| Quality +\\| Low +\\| — +\\|`),
  );
  assert.equal(pull.params.head, BRANCH);
  assert.equal(pull.params.base, 'main');
  assert.equal(pull.params.title, 'backlog: promote #62 — Add short poll links');
  assert.match(pull.params.body, /^Closes #62$/m);
  assert.equal(comment, '');
  assert.equal(core.failed, null);
  assert.deepEqual(core.notices, [`Opened https://github.com/${REPOSITORY}/pull/70`]);
});

test('a split recommendation gets consecutive IDs and a counted title', async () => {
  const backlog = parseBacklog(realBacklog);
  const comments = [triageComment(triageBody({ entries: [{}, { Title: 'Second item' }] }))];
  const { result } = await promote62(fakeGitHub({ comments }));
  const expected = [nextBacklogId(backlog), nextBacklogId(backlog) + 1];

  assert.deepEqual(
    result.plan.entries.map((entry) => entry.ID),
    expected.map(String),
  );
  assert.equal(result.plan.title, 'backlog: promote #62 (2 items)');
});

test('IDs added by open pull requests of this repository are skipped; forks are ignored', async () => {
  const backlog = parseBacklog(realBacklog);
  const github = fakeGitHub({
    openPulls: [
      { number: 65, head: { repo: { full_name: REPOSITORY } } },
      { number: 66, head: { repo: { full_name: 'someone/fork' } } },
      { number: 67, head: { repo: null } },
    ],
    pullFiles: {
      65: [{ filename: BACKLOG_PATH, patch: '@@ -1 +1 @@\n+| 36  | Other promotion |' }],
      66: [{ filename: BACKLOG_PATH, patch: '@@ -1 +1 @@\n+| 99  | Fork row |' }],
    },
  });
  const { result } = await promote62(github);

  assert.equal(result.plan.entries[0].ID, String(nextBacklogId(backlog)));
});

test('a dry run reads everything and writes nothing', async () => {
  const backlog = parseBacklog(realBacklog);
  const nextId = nextBacklogId(backlog);
  const github = fakeGitHub();
  const { result, core, comment } = await promote62(github, { dryRun: true });

  assert.equal(result.outcome, 'dry-run');
  assert.ok(github.state.calls.every(({ route }) => route.startsWith('GET ')));
  assert.equal(comment, '');
  assert.match(core.summaryText, /Would open: backlog: promote #62 — Add short poll links/);
  assert.match(core.summaryText, new RegExp(`\\| ${nextId} {2}\\| Add short poll links`));
  assert.equal(core.failed, null);
});

test('a refused dry run reports the reason in the summary only', async () => {
  const github = fakeGitHub({ comments: [triageComment(ISSUE_62_TRIAGE)] });
  const { result, core, comment } = await promote62(github, { dryRun: true });

  assert.equal(result.outcome, 'refused');
  assert.equal(comment, '');
  assert.match(core.summaryText, /Notes is 54 characters/);
  assert.ok(core.failed);
});

// Each refusal: [name, fake GitHub options, expected reason, expected recovery]
const refusals = [
  [
    'a trigger without admin access',
    { permission: 'write' },
    /`avshukan` started promotion with `write` access; only a repository admin/,
    /A repository admin should remove and re-apply the `triage: accepted` label/,
  ],
  [
    'a closed Issue',
    { issue: { state: 'closed' } },
    /Issue #62 is closed/,
    /Reopen the Issue, then remove and re-apply/,
  ],
  [
    'an Issue without the accepted label',
    { issue: { labels: [] } },
    /does not carry the `triage: accepted` label/,
    /Apply the `triage: accepted` label/,
  ],
  [
    'a pull request number',
    { issue: { pull_request: {} } },
    /#62 is a pull request, not an Issue/,
    /Run the workflow with an Issue number/,
  ],
  [
    'a leftover branch of a closed promotion',
    { promotionPulls: [{ number: 64, state: 'closed', merged_at: null }], branches: [BRANCH] },
    /The `docs\/backlog-promote-62` branch already exists \(left from closed pull request #64\)/,
    /Delete the `docs\/backlog-promote-62` branch, then remove and re-apply/,
  ],
  [
    'an Issue without a triage recommendation',
    { comments: [triageComment(undefined, { user: { login: 'avshukan', type: 'User' } })] },
    /has no triage recommendation from the `issue-triage` workflow/,
    /re-run it from the Actions tab, then remove and re-apply/,
  ],
  [
    'two triage recommendations',
    { comments: [triageComment(), triageComment(undefined, { id: 2 })] },
    /has 2 triage recommendations .*promotion needs exactly one/,
    /Delete the stale triage comments so that exactly one remains, then remove and re-apply/,
  ],
  [
    'a Duplicate verdict',
    { comments: [triageComment(triageBody({ verdict: 'Duplicate of ID-2' }))] },
    /The triage verdict is `Duplicate of ID-2`; only `Keep` can be promoted/,
    /remove the `triage: accepted` label\. To promote anyway, edit the \[triage comment\]/,
  ],
  [
    'overlong Notes (the real #62 recommendation)',
    { comments: [triageComment(ISSUE_62_TRIAGE)] },
    /Notes is 54 characters; the `Todo` Notes column fits 51: `Replace\/alias UUID with short ID; needs redirect layer`/,
    /Edit the \[triage comment\]\([^)]+\) to fix the values above \(promotion never shortens or rewrites them\), then remove and re-apply the `triage: accepted` label \(or run the \*\*Backlog promotion\*\* workflow from the Actions tab with `issue: 62` and `dry_run` unchecked\)/,
  ],
  [
    'a backlog that already breaks its format',
    { backlog: realBacklog.replace('| 6   |', '| 19  |') },
    /does not follow its own `Format` rules.*\n\n- Todo line \d+: ID 19 is already used/s,
    /Fix `docs\/backlog.md` on `main` in a docs pull request, then remove and re-apply/,
  ],
  [
    'an open pull request whose backlog diff is unavailable',
    {
      openPulls: [{ number: 65, head: { repo: { full_name: REPOSITORY } } }],
      pullFiles: { 65: [{ filename: BACKLOG_PATH }] },
    },
    /Open pull request #65 changes `docs\/backlog.md`, but GitHub returned no diff/,
    /Merge or close #65, then remove and re-apply/,
  ],
  [
    'an unexpected API error',
    {
      failures: {
        'GET /repos/{owner}/{repo}/issues/{issue_number}/comments': httpError(502, 'Bad Gateway'),
      },
    },
    /Unexpected error: `Bad Gateway`/,
    /Re-run the failed jobs of this workflow run from the Actions tab/,
  ],
];

for (const [name, options, reason, recovery] of refusals) {
  test(`refuses ${name} without changing anything`, async () => {
    const github = fakeGitHub(options);
    const { result, core, comment } = await promote62(github);

    assert.equal(result.outcome, 'refused');
    assert.deepEqual(github.writes(), []);
    assert.match(comment, /^### Backlog promotion failed/);
    assert.match(comment, reason);
    assert.match(comment, recovery);
    assert.match(comment, /Nothing in the repository was changed\./);
    assert.ok(core.failed);
  });
}

for (const [state, pull, reason] of [
  ['open', { number: 64, state: 'open' }, /Promotion pull request #64 is already open/],
  [
    'merged',
    { number: 64, state: 'closed', merged_at: '2026-09-30T10:00:00Z' },
    /already promoted by #64/,
  ],
]) {
  test(`does nothing when a promotion pull request is already ${state}`, async () => {
    const github = fakeGitHub({ promotionPulls: [pull], branches: [BRANCH] });
    const { result, core, comment } = await promote62(github);

    assert.equal(result.outcome, 'noop');
    assert.deepEqual(github.writes(), []);
    assert.match(comment, /^### Backlog promotion: nothing to do/);
    assert.match(comment, reason);
    assert.match(comment, /\*\*Recovery:\*\* Nothing to do/);
    assert.equal(core.failed, null);
  });
}

test('a closed promotion can be retried once its branch is deleted', async () => {
  const github = fakeGitHub({ promotionPulls: [{ number: 64, state: 'closed', merged_at: null }] });
  const { result } = await promote62(github);

  assert.equal(result.outcome, 'promoted');
});

test('a branch created by a concurrent run stops the promotion', async () => {
  const github = fakeGitHub({
    failures: { 'POST /repos/{owner}/{repo}/git/refs': httpError(422, 'Reference already exists') },
  });
  const { result, comment } = await promote62(github);

  assert.equal(result.outcome, 'refused');
  assert.match(comment, /appeared while promotion was running/);
  assert.match(comment, /If there is none, delete the `docs\/backlog-promote-62` branch/);
});

test('a failed pull request deletes the new branch and names the missing setting', async () => {
  const github = fakeGitHub({
    failures: {
      'POST /repos/{owner}/{repo}/pulls': httpError(
        403,
        'GitHub Actions is not permitted to create or approve pull requests.',
      ),
    },
  });
  const { result, comment } = await promote62(github);

  assert.equal(result.outcome, 'refused');
  assert.deepEqual(github.writes(), [
    'POST /git/refs',
    `PUT /contents/${BACKLOG_PATH}`,
    'POST /pulls',
    `DELETE /git/refs/heads/${BRANCH}`,
  ]);
  assert.equal(github.state.branches.size, 0);
  assert.match(comment, /was deleted again/);
  assert.match(comment, /Nothing in the repository was changed\./);
  assert.match(
    comment,
    /A repository admin enables Settings → Actions → General → Workflow permissions → \*\*Allow GitHub Actions to create and approve pull requests\*\*, then remove and re-apply/,
  );
});

test('a failed clean-up tells the owner to delete the branch', async () => {
  const github = fakeGitHub({
    failures: {
      [`PUT /repos/{owner}/{repo}/contents/${BACKLOG_PATH}`]: httpError(409, 'Conflict'),
      [`DELETE /repos/{owner}/{repo}/git/refs/heads/${BRANCH}`]: httpError(500, 'Server Error'),
    },
  });
  const { comment } = await promote62(github);

  assert.match(
    comment,
    /Deleting the `docs\/backlog-promote-62` branch it had created also failed/,
  );
  assert.doesNotMatch(comment, /Nothing in the repository was changed/);
  assert.match(comment, /Delete the `docs\/backlog-promote-62` branch, then remove and re-apply/);
});

test('the workflow entry point reads the labeled event and the dispatch inputs', async () => {
  const labeled = await run({ github: fakeGitHub(), context: fakeContext(), core: fakeCore() });
  assert.equal(labeled.outcome, 'promoted');

  const dispatch = (inputs) =>
    fakeContext({
      eventName: 'workflow_dispatch',
      payload: { sender: { login: 'avshukan' }, repository: { default_branch: 'main' }, inputs },
    });
  const dryRun = await run({
    github: fakeGitHub(),
    context: dispatch({ issue: '62', dry_run: 'true' }),
    core: fakeCore(),
  });
  assert.equal(dryRun.outcome, 'dry-run');

  const real = await run({
    github: fakeGitHub(),
    context: dispatch({ issue: '62', dry_run: false }),
    core: fakeCore(),
  });
  assert.equal(real.outcome, 'promoted');

  const core = fakeCore();
  const invalid = await run({ github: fakeGitHub(), context: dispatch({ issue: 'x' }), core });
  assert.equal(invalid.outcome, 'invalid');
  assert.match(core.failed, /No valid Issue number/);
});
